name: Multi-cluster K8S Deploy

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Action to perform"
        required: true
        type: choice
        default: "test-only"
        options:
          - deploy
          - destroy
          - test-only
      cloud:
        description: "Cloud"
        required: true
        type: choice
        default: "AWS"
        options:
          - GCP
          - AWS
      env_type:
        description: "Environment type (tfvars file name must adhere to 'env_type-env_number.tfvars'. ex. 'dev-01.tfvars')"
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod
      env_number:
        description: "K8S environment (cluster) number (e.g. 01 for dev-01, 02 for dev-02)"
        required: true
        type: string
      endpoint_access:
        description: "Control plane endpoint access [AWS only]"
        required: false
        type: choice
        default: "public"
        options:
          - public
          - private

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
permissions:
  contents: read
  id-token: write   # Required for OIDC (both GCP WIF and AWS OIDC)

jobs:
  # ─────────────────────────────────────────────
  # Shared validation (runs for both clouds)
  # ─────────────────────────────────────────────
  validate:
    name: Validate Inputs
    runs-on: ubuntu-latest
    steps:
      - name: Validate K8S cluster name
        run: |
          env_name="${{ inputs.env_type }}-${{ inputs.env_number }}"

          if [[ ! "$env_name" =~ ^[a-z]([-a-z0-9]{0,38}[a-z0-9])?$ ]]; then
            echo "❌ Invalid K8S cluster name: $env_name"
            echo "Rules:"
            echo " - 1–40 characters"
            echo " - lowercase letters, numbers, hyphens"
            echo " - must start with a letter"
            echo " - must not end with a hyphen"
            exit 1
          fi
          echo "✅ K8S cluster name is valid: $env_name"

  # ─────────────────────────────────────────────
  # AWS / EKS Job
  # ─────────────────────────────────────────────
  terraform-aws:
    name: "Terraform [AWS/EKS ${{ inputs.endpoint_access }} Endpoints Setup]"
    runs-on: ubuntu-latest
    needs: validate
    if: inputs.cloud == 'AWS' && inputs.action != 'test-only'
    
    defaults:
      run:
        # Use the input to pick the right directory dynamically
        working-directory: ./aws/terraform/${{ inputs.endpoint_access }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Authenticate to AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="key=${{ inputs.endpoint_access }}/${{ inputs.env_type }}/${{ inputs.env_number }}/terraform.tfstate" # ex. public/dev/01/terraform.tfstate

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: inputs.action == 'deploy'
        run: |
          terraform plan \
            -var-file="../envs/${{ inputs.env_type }}-${{ inputs.env_number }}.tfvars" \
            -var="region=${{ vars.AWS_REGION }}" \
            -var="endpoint_access=${{ inputs.endpoint_access }}" \
            -var="env_type=${{ inputs.env_type }}" \
            -var="env_number=${{ inputs.env_number }}" \
            -out=tfplan

      - name: Terraform Apply
        if: inputs.action == 'deploy' && github.ref == 'refs/heads/main'
        run: |
          terraform apply \
          -auto-approve \
          tfplan

      - name: Terraform Destroy
        if: inputs.action == 'destroy' && github.ref == 'refs/heads/main'
        run: |
          terraform destroy \
            -var-file="../envs/${{ inputs.env_type }}-${{ inputs.env_number }}.tfvars" \
            -var="region=${{ vars.AWS_REGION }}" \
            -var="endpoint_access=${{ inputs.endpoint_access }}" \
            -var="env_type=${{ inputs.env_type }}" \
            -var="env_number=${{ inputs.env_number }}" \
            -auto-approve

  test-private-cluster:
    name: "Test Private EKS via Bastion"
    runs-on: ubuntu-latest
    #needs: terraform-aws
    # Only run for AWS when endpoint_access is 'private'
    if: (inputs.action == 'deploy' || inputs.action == 'test-only') && inputs.cloud == 'AWS' && inputs.endpoint_access == 'private'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Authenticate to AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Get cluster config
        run: |
          aws ec2-instance-connect ssh \
            --os-user ec2-user \
            --connection-type eice \
            --instance-id i-0103990515b68ad79
            -- -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "echo 'Connection successful'"

#          #aws sts get-caller-identity
#          #aws eks update-kubeconfig --name ${{inputs.env_type}}-${{inputs.env_number}} --region ${{vars.AWS_REGION}}
#          #kubectl get nodes

#
#  # ─────────────────────────────────────────────
#  # AWS / EKS - Public endpoint
#  # ─────────────────────────────────────────────
#  terraform-aws-public:
#    name: "Terraform [EKS Public Endpoints]"
#    runs-on: ubuntu-latest
#    needs: validate
#    if: inputs.cloud == 'AWS' && inputs.endpoint_access == 'public'
#
#    defaults:
#      run:
#        working-directory: ./aws/terraform/public
#
#    #env:
#      #TF_VAR_region: ${{ vars.AWS_REGION }}
#      #TF_VAR_env_type: ${{ inputs.env_type }}
#      #TF_VAR_env_number: ${{ inputs.env_number }}
#      #TF_VAR_endpoint_access: ${{ inputs.endpoint_access }}
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v6
#
#      - name: Authenticate to AWS (OIDC)
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
#          aws-region: ${{ vars.AWS_REGION }}
#
#      - name: Set up Terraform
#        uses: hashicorp/setup-terraform@v4
#        with:
#          terraform_version: 1.14
#
#      - name: Terraform Init
#        run: |
#          terraform init \
#            -backend-config="key=${{inputs.endpoint_access}}/${{ inputs.env_type }}/${{ inputs.env_number }}/terraform.tfstate" # ex. public/dev/01/terraform.tfstate
#
#      - name: Terraform Validate
#        run: terraform validate
#
#      - name: Terraform Plan
#        if: inputs.action == 'deploy'
#        run: |
#          terraform plan \
#            -var="region=${{ vars.AWS_REGION }}" \
#            -var="endpoint_access=${{ inputs.endpoint_access }}" \
#            -var="env_type=${{ inputs.env_type }}" \
#            -var="env_number=${{ inputs.env_number }}" \
#            -var-file="../envs/${{ inputs.env_type }}-${{ inputs.env_number }}.tfvars" \
#            -out=tfplan
#
#      - name: Terraform Apply
#        if: inputs.action == 'deploy' && github.ref == 'refs/heads/main'
#        run: |
#          terraform apply \
#            -auto-approve \
#            tfplan
#
#      - name: Terraform Destroy
#        if: inputs.action == 'destroy' && github.ref == 'refs/heads/main'
#        run: |
#          terraform destroy \
#            -var="region=${{ vars.AWS_REGION }}" \
#            -var="endpoint_access=${{ inputs.endpoint_access }}" \
#            -var="env_type=${{ inputs.env_type }}" \
#            -var="env_number=${{ inputs.env_number }}" \
#            -var-file="../envs/${{ inputs.env_type }}-${{ inputs.env_number }}.tfvars" \
#            -auto-approve
#
#  # ─────────────────────────────────────────────
#  # AWS / EKS - Private endpoint
#  # ─────────────────────────────────────────────
#  terraform-aws-private:
#    name: "Terraform [EKS Private Endpoints]"
#    runs-on: ubuntu-latest
#    needs: validate
#    if: inputs.cloud == 'AWS' && inputs.endpoint_access == 'private'
#
#    defaults:
#      run:
#        working-directory: ./aws/terraform/private
#
#    env:
#      TF_VAR_region: ${{ vars.AWS_REGION }}
#      TF_VAR_env_type: ${{ inputs.env_type }}
#      TF_VAR_env_number: ${{ inputs.env_number }}
#      TF_VAR_endpoint_access: ${{ inputs.endpoint_access }}
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v6
#
#      - name: Authenticate to AWS (OIDC)
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
#          aws-region: ${{ vars.AWS_REGION }}
#
#      - name: Set up Terraform
#        uses: hashicorp/setup-terraform@v4
#        with:
#          terraform_version: 1.14
#
#      - name: Terraform Init
#        run: |
#          terraform init \
#            -backend-config="key=${{inputs.endpoint_access}}/${{ inputs.env_type }}/${{ inputs.env_number }}/terraform.tfstate"
#
#      - name: Terraform Validate
#        run: terraform validate
#
#      - name: Terraform Plan
#        if: inputs.action == 'deploy'
#        run: |
#          terraform plan \
#            -var="env_type=${{ inputs.env_type }}" \
#            -var="env_number=${{ inputs.env_number }}" \
#            -var-file="../envs/${{ inputs.env_type }}-${{ inputs.env_number }}.tfvars" \
#            -out=tfplan
#
#      - name: Terraform Apply
#        if: inputs.action == 'deploy' && github.ref == 'refs/heads/main'
#        run: |
#          terraform apply \
#            -auto-approve \
#            tfplan
#
#      - name: Terraform Destroy
#        if: inputs.action == 'destroy' && github.ref == 'refs/heads/main'
#        run: |
#          terraform destroy \
#            -var="env_type=${{ inputs.env_type }}" \
#            -var="env_number=${{ inputs.env_number }}" \
#            -var-file="../envs/${{ inputs.env_type }}-${{ inputs.env_number }}.tfvars" \
#            -auto-approve
#
  # ─────────────────────────────────────────────
  # GCP / GKE Job
  # ─────────────────────────────────────────────
  terraform-gcp:
    name: "Terraform [GCP/GKE]"
    runs-on: ubuntu-latest
    needs: validate
    if: inputs.cloud == 'GCP'

    defaults:
      run:
        working-directory: gcp

    env:
      TF_VAR_project_id: ${{ vars.GCP_PROJECT_ID }}
      TF_VAR_region: ${{ vars.GCP_REGION }}
      TF_VAR_runner_service_account: ${{ vars.GCP_RUNNER_SERVICE_ACCOUNT }}
      TF_VAR_env_type: ${{ inputs.env_type }}
      TF_VAR_env_number: ${{ inputs.env_number }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v3
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          workload_identity_provider: projects/${{ vars.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: ${{ vars.GCP_RUNNER_SERVICE_ACCOUNT }}@${{ vars.GCP_PROJECT_ID }}.iam.gserviceaccount.com

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="prefix=${{ inputs.env_type }}/${{ inputs.env_number }}"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: inputs.action == 'deploy'
        run: |
          terraform plan \
            -var-file="./envs/${{ inputs.env_type }}-${{ inputs.env_number }}.tfvars" \
            -var="env_type=${{ inputs.env_type }}" \
            -var="env_number=${{ inputs.env_number }}" \
            -out=tfplan

      - name: Terraform Apply
        if: inputs.action == 'deploy' && github.ref == 'refs/heads/main'
        run: |
          terraform apply \
            -auto-approve \
            tfplan

      - name: Terraform Destroy
        if: inputs.action == 'destroy' && github.ref == 'refs/heads/main'
        run: |
          terraform destroy \
            -var-file="./envs/${{ inputs.env_type }}-${{ inputs.env_number }}.tfvars" \
            -var="env_type=${{ inputs.env_type }}" \
            -var="env_number=${{ inputs.env_number }}" \
            -auto-approve

#      - name: Stop workflow
#        run: |
#          echo "Intentional stop"
#          exit 0
#####################################  

#      - name: Set up gcloud
#        uses: google-github-actions/setup-gcloud@v2
#        with:
#          install_components: gke-gcloud-auth-plugin
#          
#      - name: Get K8S credentials
#        run: |
#          gcloud container clusters get-credentials \
#            ${{inputs.env_type}}-${{inputs.env_number}} \
#            --location $(terraform output -raw cluster_location) \
#            --project ${{ vars.PROJECT_ID }}
#
#      - name: Verify cluster access
#        run: |
#          kubectl version --client
#          kubectl get nodes  
                              